BASE_URL = "https://api.crunchbase.com/v4/data/static_exports"

# Keyed by a normalized collection identifier
COLLECTIONS = {
    "acquisition_predictions": f"{BASE_URL}/acquisition_predictions.zip",
    "acquisitions": f"{BASE_URL}/acquisitions.zip",
    "addresses": f"{BASE_URL}/addresses.zip",
    "awards": f"{BASE_URL}/awards.zip",
    "categories": f"{BASE_URL}/categories.zip",
    "category_groups": f"{BASE_URL}/category_groups.zip",
    "closure_predictions": f"{BASE_URL}/closure_predictions.zip",
    "degrees": f"{BASE_URL}/degrees.zip",
    "diversity_spotlights": f"{BASE_URL}/diversity_spotlights.zip",
    "event_appearances": f"{BASE_URL}/event_appearances.zip",
    "events": f"{BASE_URL}/events.zip",
    "funds": f"{BASE_URL}/funds.zip",
    "funding_predictions": f"{BASE_URL}/funding_predictions.zip",
    "funding_rounds": f"{BASE_URL}/funding_rounds.zip",
    "growth_insights": f"{BASE_URL}/growth_insights.zip",
    "growth_predictions": f"{BASE_URL}/growth_predictions.zip",
    "investments": f"{BASE_URL}/investments.zip",
    "investor_insights": f"{BASE_URL}/investor_insights.zip",
    "ipo_predictions": f"{BASE_URL}/ipo_predictions.zip",
    "ipos": f"{BASE_URL}/ipos.zip",
    "jobs": f"{BASE_URL}/jobs.zip",
    "key_employee_changes": f"{BASE_URL}/key_employee_changes.zip",
    "layoffs": f"{BASE_URL}/layoffs.zip",
    "layoff_predictions": f"{BASE_URL}/layoff_predictions.zip",
    "legal_proceedings": f"{BASE_URL}/legal_proceedings.zip",
    "locations": f"{BASE_URL}/locations.zip",
    "organizations": f"{BASE_URL}/organizations.zip",
    "ownerships": f"{BASE_URL}/ownerships.zip",
    "partnership_announcements": f"{BASE_URL}/partnership_announcements.zip",
    "people": f"{BASE_URL}/people.zip",
    "press_references": f"{BASE_URL}/press_references.zip",
    "principals": f"{BASE_URL}/principals.zip",
    "products": f"{BASE_URL}/products.zip",
    "product_launches": f"{BASE_URL}/product_launches.zip",
}

# Friendly display names for nicer output
COLLECTION_DISPLAY_NAMES = {
    "acquisition_predictions": "Acquisition Predictions",
    "acquisitions": "Acquisitions",
    "addresses": "Addresses",
    "awards": "Awards",
    "categories": "Categories",
    "category_groups": "Category Groups",
    "closure_predictions": "Closure Predictions",
    "degrees": "Degrees",
    "diversity_spotlights": "Diversity Spotlights",
    "event_appearances": "Event Appearances",
    "events": "Events",
    "funds": "Funds",
    "funding_predictions": "Funding Predictions",
    "funding_rounds": "Funding Rounds",
    "growth_insights": "Growth Insights",
    "growth_predictions": "Growth Predictions",
    "investments": "Investments",
    "investor_insights": "Investor Insights",
    "ipo_predictions": "IPO Predictions",
    "ipos": "IPOs",
    "jobs": "Jobs",
    "key_employee_changes": "Key Employee Changes",
    "layoffs": "Layoffs",
    "layoff_predictions": "Layoff Predictions",
    "legal_proceedings": "Legal Proceedings",
    "locations": "Locations",
    "organizations": "Organizations",
    "ownerships": "Ownerships",
    "partnership_announcements": "Partnership Announcements",
    "people": "People",
    "press_references": "Press References",
    "principals": "Principals",
    "products": "Products Insights",
    "product_launches": "Product Launches",
} 